name: CI
on: [push, pull_request]
jobs:

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.12
        uses: actions/setup-go@v1
        with:
          go-version: 1.12
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Run influxdb image
        run: 'docker run -d --name influxdb -p 9999:9999 quay.io/influxdb/influxdb:2.0.0-beta'

      - name: Creating directory for plugins
        run: 'mkdir -p ./examples/terraform.d/plugins/linux_amd64/'

      - name: Download influxdbv2-onboarding provider
        run: 'wget -qO- https://github.com/lancey-energy-storage/terraform-provider-influxdb-v2-onboarding/releases/download/v0.2.0/terraform-provider-influxdbv2-onboarding_v0.2.0-v0.2.0-linux-amd64.tar.gz | tar -xvz -C ./examples/terraform.d/plugins/linux_amd64/'

      - name: Go fmt
        run: make fmt

      - name: Initialize
        run: make initialize

      - name: Go test
        run: make test

      - name: Go testacc
        run: make testacc
